- web/sites/default/settings.local.production.php
- web/sites/default/settings.local.staging.php
- web/themes/custom/par_theme/par_theme.theme
- web/themes/custom/par_theme/sass/par.scss
A settings switch that enables the PAR green header/footer overrides over GDS template.
> PAR-872 Implement a setting to enable PAR branded heading.

- sync/views.view.helpdesk_dashboard.yml
- sync/views.view.partnership_search.yml
See new markup for screenreaders.
> PAR-882/879 - add screenreader hints to links

- sync/par_flows.par_flow.partnership_authority.yml
- web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_authority.yml
> Advice upload was going to the wrong form causing a WSOD!

- sync/par_flows.par_flow.partnership_authority.yml
- web/modules/custom/par_data/src/ParDataManager.php
- web/modules/custom/par_roles/par_roles.module
- web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_authority.yml
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsInviteForm.php
Updated logic, but we also need to discuss the invite form as it's become a bit overcrowded.
> PAR-767: Updated role assignment logic.

- web/modules/custom/par_data/src/Entity/ParDataEntity.php
- web/modules/custom/par_data/src/ParDataStorage.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParCommonTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParEnforcementNoticeTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParOrganisationTest.php
- web/modules/custom/par_data/tests/src/Kernel/ParDataTestBase.php
- web/modules/custom/par_validation/src/Plugin/Validation/Constraint/ParRequiredValidator.php
> PAR-892: Updated tests to check entity labels.

- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsDetailsForm.php
Changing some text as per mockup
> Accessibility: PAR-756 Details Screen (DO NOT MERGE)

- sync/par_data.par_data_organisation_type.organisation.yml
- web/modules/features/par_data_config/config/install/par_data.par_data_organisation_type.organisation.yml
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsEmployeeNoForm.php
> Number of employees text tweak

- tests/src/features/2-user-journey-organisation-user-update-partnership.feature
- tests/src/features/3-user-journey-partnership-update-primary-authority.feature
- tests/src/features/4-user-journey-coordinator-user-update-partnership.feature
- web/modules/custom/par_data/src/Entity/ParDataOrganisation.php
- web/modules/custom/par_flows/src/ParDisplayTrait.php
> Edit link entity titles

- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsApplicationAuthorityChecklistForm.php
Improvements to the validation of this form and also changing visible states for partnership application checklist form.
> Changes to application checklist form

- sync/par_flows.par_flow.partnership_authority.yml
- web/modules/features/par_partnership_flows/config/install/par_flows.par_flow.partnership_authority.yml
- web/modules/features/par_partnership_flows/src/Controller/ParPartnershipFlowsAdviceListController.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAboutBusinessForm.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAddressForm.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsTradingForm.php
The comment below will show which these address.
> Accessibility Tweaks

- tests/src/features/2-user-journey-organisation-user-update-partnership.feature
- tests/src/features/4-user-journey-coordinator-user-update-partnership.feature
- tests/src/features/91-enforcement-notice-management-helpdesk-user.feature
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsTradingForm.php
- Improving presentation slightly by spacing out form elements.
> PAR-764: Trading Name form contextual titles and presentation tweaks (was PR 63)

- tests/src/features/9-enforcement-notice-management-pa-user.feature
- web/modules/features/par_enforcement_flows/src/Form/ParEnforcementApproveNoticeForm.php
Testing instruction:
Checkout branch.
clear drupal cached drush cr
go to URL:  http://localhost:8111/enforcement-notice/1466/approve (for an enforcement notice in a awaiting approval state)
The lable above the allow, block, refer  should match the screen shot.
Automated tests added for regression testing.
> PAR-927: blocked

- patches/clamav_add_rest_client.patch
> fixing `Undefined property: stdClass::$stream` php error

- web/modules/custom/par_data/src/ParDataManager.php
- web/modules/custom/par_data/tests/src/Kernel/Access/AccessParPartnershipsTest.php
- web/modules/custom/par_flows/src/ParDisplayTrait.php
This temporarily removes lookup on all premises data.
> [PAR-1025 and PAR-1030]: Temp fix to remove premises data.

- .travis.yml
- cf/push.sh
- composer.json
- composer.lock
- drupal-update.sh
- sync-dev/ultimate_cron.job.dblog_cron.yml
- sync/ultimate_cron.job.comment_cron.yml
- sync/ultimate_cron.job.field_cron.yml
- sync/ultimate_cron.job.file_cron.yml
- sync/ultimate_cron.job.flysystem_cron.yml
- sync/ultimate_cron.job.google_analytics_cron.yml
- sync/ultimate_cron.job.message_cron.yml
- sync/ultimate_cron.job.node_cron.yml
- sync/ultimate_cron.job.par_actions.yml
- sync/ultimate_cron.job.par_actions_cron.yml
- sync/ultimate_cron.job.system_cron.yml
- sync/ultimate_cron.job.ultimate_cron_cron.yml
- sync/ultimate_cron.job.xmlsitemap_cron.yml
- sync/xmlsitemap.xmlsitemap.g3XYqcXbSKPVBDODwnT6pq7oqhCFkPryj4vVqrl_Kfc.yml
- tools/cron_runner.py
Patch here will also need review - https://www.drupal.org/project/drupal/issues/2928889#comment-12372748
This can be tested by going to http://par.localhost/admin/config/system/cron/jobs and running cron (each job separately if you have to). There should be no errors or red crosses by the end.
> PAR-1009: Updated cron frequencies and errors.

- .travis.yml
Added in travis config lines for parallel job runs for cucumber and jmeter
> PAR-1047 Added in travis config lines for parallel job runs

- sync/par_flows.par_flow.approve_enforcement.yml
- tests/src/features/1-enforcement-officer-to-primary-enforcement-officer-new-legal-entity.feature
- tests/src/features/9-enforcement-notice-management-pa-user.feature
- tests/src/features/91-enforcement-notice-management-helpdesk-user.feature
- web/modules/features/par_enforcement_flows/config/install/par_flows.par_flow.approve_enforcement.yml
> PAR-1013: Readded tests without commenting out.

- composer.json
- composer.lock
Patch already applied on Drupal 8.4.3, so I removed the patch.
> Upgrade to Drupal 8.4.3

- tests/src/features/1-enforcement-officer-to-primary-enforcement-officer-new-legal-entity.feature
- tests/src/features/6-enforcement-officer-to-coordinator-user-existing-legal-entity.feature
- tests/src/features/7-enforcement-officer-to-primary-authority-user-existing-legal-entity.feature
- tests/src/features/8-enforcement-officer-to-primary-authority-user-new-legal-entity.feature
- web/modules/custom/par_data/src/Entity/ParDataEnforcementAction.php
- web/modules/custom/par_data/src/Entity/ParDataEnforcementNotice.php
- web/modules/features/par_enforcement_flows/src/Form/ParEnforcementAddActionForm.php
- web/modules/features/par_enforcement_flows/src/Form/ParEnforcementRaiseNoticeDetailsForm.php
- web/modules/features/par_enforcement_flows/src/Form/ParEnforcementRaiseNoticeForm.php
> PAR-1073 resolve issue of actions being created without titles

- sync/views.view.par_user_partnerships.yml
- sync/views.view.partnership_search.yml
- sync/views.view.public_register.yml
- web/modules/custom/par_notification/src/EventSubscriber/NewEnforcementSubscriber.php
> [PAR-1084] Revoked partnerships are not appearing when using "Revoked" filter from Helpdesk user dashboard

- web/modules/custom/par_flows/src/Form/ParBaseForm.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAddressForm.php
Change PAR-1109 to prevent any nation being saved for UK (forgot `Other` is long gone option)
> PAR-1109 Changes

- sync/core.entity_form_display.par_data_partnership.partnership.default.yml
- sync/field.field.par_data_partnership.partnership.field_legal_entity.yml
- sync/field.storage.par_data_partnership.field_legal_entity.yml
- web/modules/custom/par_data/par_data.install
- web/modules/custom/par_data/src/Entity/ParDataPartnership.php
- web/modules/features/par_data_config/config/install/core.entity_form_display.par_data_partnership.partnership.default.yml
- web/modules/features/par_data_config/config/install/field.field.par_data_partnership.partnership.field_legal_entity.yml
- web/modules/features/par_data_config/config/install/field.storage.par_data_partnership.field_legal_entity.yml
- web/modules/features/par_enforcement_flows/src/Controller/ParEnforcementFlowsPartnershipPageController.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsDetailsForm.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsLegalEntityForm.php
entities should live on the partnership, changing form submit hander.
> [PAR-1111] Use partnership entity to store legal entity references.

- sync/user.role.par_helpdesk.yml
- sync/views.view.helpdesk_dashboard.yml
- web/modules/custom/par_roles/par_roles.permissions.yml
- web/modules/features/par_rd_help_desk_flows/par_rd_help_desk_flows.info.yml
- web/modules/features/par_rd_help_desk_flows/par_rd_help_desk_flows.routing.yml
- web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskRevokeForm.php
replaced RD Help Desk to Help Desk
> rd helpdesk to helpdesk

- tests/src/features/1-user-journey-organisation-user-complete-partnership-business-details.feature
- tests/src/features/4-user-journey-coordinator-user-complete-partnership-business-details.feature
- web/modules/features/par_partnership_confirmation_flows/src/Form/ParConfirmationReviewForm.php
Massive oopsie, this was raised three months ago, need to get this in first (and into the release).
> PAR-931: Added terms and conditions to apply journey.

- web/modules/custom/par_flows/src/Form/ParBaseForm.php
- web/modules/custom/par_forms/src/Plugin/ParForm/ParEmployeeNumberForm.php
- web/modules/custom/par_forms/src/Plugin/ParForm/ParLegalEntityForm.php
- web/modules/custom/par_forms/src/Plugin/ParForm/ParSicCodeForm.php
- web/modules/features/par_partnership_confirmation_flows/src/Form/ParLegalEntityForm.php
- web/modules/features/par_partnership_confirmation_flows/src/Form/ParSelectLegalEntitiesForm.php
Validation bug required for release.
> PAR-1177: Updated validation bugs.

- sync/core.entity_view_display.message.partnership_approved_notificatio.default.yml
- sync/core.entity_view_display.message.partnership_approved_notificatio.full.yml
- sync/core.entity_view_display.message.partnership_approved_notificatio.mail_body.yml
- sync/core.entity_view_display.message.partnership_confirmed_notificati.default.yml
- sync/core.entity_view_display.message.partnership_confirmed_notificati.full.yml
- sync/core.entity_view_display.message.partnership_confirmed_notificati.mail_subject.yml
- web/modules/custom/par_notification/par_notification.services.yml
- web/modules/custom/par_notification/src/EventSubscriber/PartnershipApplicationCompletedSubscriber.php
This PR resolves all the notification issues.
> PAR-1185 hotfix

- sync/core.entity_view_display.par_data_coordinated_business.coordinated_business.default.yml
- sync/par_data.par_data_coordinated_business_type.coordinated_business.yml
- sync/par_flows.par_flow.member_add.yml
- web/modules/custom/par_forms/src/Plugin/ParForm/ParCoveredByPlanForm.php
- web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_coordinated_business.coordinated_business.default.yml
- web/modules/features/par_data_config/config/install/par_data.par_data_coordinated_business_type.coordinated_business.yml
- web/modules/features/par_member_add_flows/config/install/par_flows.par_flow.member_add.yml
- web/modules/features/par_member_add_flows/src/Form/ParConfirmationReviewForm.php
> PAR-1195: Added covered by form.

- web/modules/custom/par_forms/src/Plugin/ParForm/ParAddressForm.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAddressForm.php
Removed 'your' from business address form text
> New organisation information

- CODEOWNERS
- sync/views.view.partnership_search.yml
- tests/src/features/10-enforcement-officer-to-primary-enforcement-officer-new-legal-entity.feature
- tests/src/features/51-user-journey-partnership-update-primary-authority.feature
- tests/src/features/52-user-journey-coordinator-user-upload-partnership.feature
- tests/src/features/60-enforcement-officer-to-coordinator-user-existing-legal-entity.feature
- tests/src/features/70-enforcement-officer-to-primary-authority-user-existing-legal-entity.feature
- tests/src/features/81-enforcement-officer-to-primary-authority-user-new-legal-entity.feature
- tests/src/features/91-partnerships-approval-helpdesk-user.feature
This includes work to complete PAR-433, PAR-1236, PAR-1115, PAR-853, PAR-992
This does not include any resolutions for PAR-1020, Member Searching, which would need a separate search page just for coordinated partnerships (because members are not a required relationship in the main search, thus the member name isn't always present and searchable).
And does not include any resolutions for PAR-1125, Fuzzy Searching, which would need a more powerful search index such Elastic Search to accomplish.
> PAR-1237: Spike into more advanced search

- sync/views.view.partnership_search.yml
- web/modules/custom/par_data/src/Entity/ParDataEntity.php
- web/modules/features/par_member_upload_flows/src/ParMemberCsvHandler.php
* Corrected index number displayed when errors occur.
* Corrected column names when there is an error with legal entities.
* Filtered user input.
* Re-enabled lock.
* Added coordinated members to the partnership search.
* Corrected an edge case bug when rendering entity label()
> PAR-1202: More member upload bug fixes

- web/modules/features/par_member_upload_flows/src/ParMemberCsvHandler.php
This resolves:
* Saving the value entered for 'Covered by Inspection Plan' correctly.
* Saving members correctly when more than 50 in the CSV.
* Adding lock when processing fewer than 50 members.
* Corrected bug that only uploaded the last 100 members in the CSV.
> PAR-1202: Updated more bugs.

- composer.json
- composer.lock
See - https://www.drupal.org/project/flysystem/issues/2955174#comment-12568197
Patch has now been committed.
> Removed patch that is now applied.

- web/modules/features/par_enforcement_flows/src/Form/ParEnforcementApproveNoticeForm.php
> PAR-1124 approve notification summary field added

- sync/user.role.par_authority.yml
- web/modules/custom/par_roles/par_roles.permissions.yml
- web/modules/features/par_dashboards/src/Controller/ParDashboardsDashboardController.php
Old PR closed:  https://github.com/UKGovernmentBEIS/beis-primary-authority-register/pull/268
Jira Ticket:  https://regulatorydelivery.atlassian.net/browse/PAR-1251
Updated designs:   https://primary-authority.herokuapp.com/dashboard
Outcome of code updates:
> PAR-1251 Enquiry permissions + contextual dashboard link

- web/modules/features/par_enforcement_flows/src/Form/ParEnforcementSubmitNoticeForm.php
> PAR-914 form updates on enforcement notifications confirm page

- web/modules/custom/par_data_test/content/par_data_organisation/b70654f7-4970-4eb5-860c-2fad78ea52fc.json
- web/modules/custom/par_data_test/content/par_data_organisation/c5615ef2-59a5-4786-9bb2-95d8ef011531.json
- web/modules/custom/par_data_test/content/par_data_partnership/310ed8cc-3ec7-4857-ac83-9e66a16f9cbe.json
- web/modules/custom/par_data_test/content/par_data_partnership/336989f4-1bf8-453f-9e81-269b588d526d.json
- web/modules/custom/par_data_test/content/par_data_person/26db3fbe-d4a6-4a6a-ad69-108b54e1e4c5.json
- web/modules/custom/par_data_test/content/par_data_person/2705c28a-8ee6-4b4d-be80-93b11be48937.json
- web/modules/custom/par_data_test/content/par_data_person/3f21083a-98c9-440e-92b0-12947f799e0a.json
- web/modules/custom/par_data_test/content/par_data_person/42f41471-4b62-432b-8ca3-bf3b34b5fdd1.json
- web/modules/custom/par_data_test/content/par_data_person/512ccfa3-496d-47aa-9a46-6abfa8922625.json
- web/modules/custom/par_data_test/content/par_data_person/8cbcde93-3a33-45ff-9503-02ce78d9a46f.json
- web/modules/custom/par_data_test/content/par_data_person/9798a6c5-2978-496f-b1ee-b1fb31802f9f.json
- web/modules/custom/par_data_test/content/par_data_person/b36d8ee5-b8ff-4dd7-9851-303c66a3497a.json
- web/modules/custom/par_data_test/content/par_data_person/c78b0352-15c8-42b5-b22d-082b72c51af4.json
- web/modules/custom/par_data_test/content/par_data_person/d2f48b3a-799c-43ca-ae08-8df30ecbbfbc.json
- web/modules/custom/par_data_test/content/par_data_premises/7b24f86d-784d-444a-be17-90ee3331ab66.json
- web/modules/custom/par_data_test/content/par_data_premises/a81765cb-8b61-4641-8732-08ac68606041.json
- web/modules/custom/par_data_test/content/user/0001930d-a58d-4bc4-8d99-d14a3349d0ce.json
- web/modules/custom/par_data_test/content/user/091031a0-6f43-4632-ac3d-67d635a6fa5a.json
- web/modules/custom/par_data_test/content/user/1a6dc8cd-fea2-486b-bd0e-12572c6a26ab.json
- web/modules/custom/par_data_test/content/user/29eff252-81b3-4e73-afd1-8b902e19e66b.json
- web/modules/custom/par_data_test/content/user/44f38230-a289-4dc9-b3fa-1f0475c8a31e.json
- web/modules/custom/par_data_test/content/user/46e65664-bf34-4713-ab14-740cbe581538.json
- web/modules/custom/par_data_test/content/user/644b83e2-f942-4545-a70e-ecbbb598a29d.json
- web/modules/custom/par_data_test/content/user/82eb9524-9acc-4057-9754-ad3c839b66b8.json
- web/modules/custom/par_data_test/content/user/bfc29972-fe7d-4b47-9e62-b3fa3628476b.json
- web/modules/custom/par_forms/src/Plugin/ParForm/ParEnforcementActionDetail.php
- web/modules/custom/par_forms/src/Plugin/ParForm/ParEnforcementActionForm.php
- web/modules/custom/par_forms/src/Plugin/ParForm/ParLegalEntityForm.php
- web/modules/custom/par_forms/src/Plugin/ParForm/ParSicCodeForm.php
- web/modules/custom/par_forms/src/Plugin/ParForm/ParTradingNameForm.php
> PAR-1310: Added optional to all multiple form elements.

- devops/cf/README.md
- devops/cf/push.sh
- devops/cf/route.sh
- devops/dashboard/config/dashboard.php
- tests/nfr/jmeter/load-test-plan-staging.jmx
- tests/nfr/jmeter/load-test-plan.jmx
- web/sites/default/settings.php
Just a search and replace across the project.
> Change from par-beta.co.uk to .net for alts

- sync/views.view.par_user_enforcements.yml
- web/CHANGELOG.md
- web/modules/custom/par_actions/src/Plugin/Action/ParApproveAction.php
- web/modules/custom/par_actions/src/Plugin/Action/ParApproveEntity.php
- web/modules/custom/par_data/src/Entity/ParDataEnforcementNotice.php
- web/modules/custom/par_data/src/Entity/ParDataEntity.php
- web/modules/custom/par_data/src/Plugin/views/field/ParDataStatusAuthor.php
- web/modules/custom/par_forms/src/Plugin/ParForm/ParEnforcementActionDetail.php
> PAR-1333: Adding status author to enforcement listings.

- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAdviceForm.php
Required form validation fixes.
> PAR-1379 (sub task for PAR-934) implement form validation fixes

- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAdviceUploadForm.php
> PAR-1158 external template links

- composer.json
- composer.lock
https://www.drupal.org/project/flysystem/issues/3061561#comment-13145851
> PAR-1376: Maintenance page has no styling

- devops/cf/manifests/manifest.production.yml
- devops/cf/push.local.sh
Don't merge quite yet, want to think about this some more.
> PAR-1421: Updated push script.

- web/modules/custom/par_forms/src/Plugin/ParForm/ParDedupePersonForm.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsDetailsForm.php
> Release branch (Merge once release v32.0 goes out)

- web/modules/custom/par_login/par_login.module
- web/modules/custom/par_login/src/Plugin/Menu/ParAccountLink.php
> PAR-1465: Changed all username display to email address.

- web/modules/custom/par_data/src/Entity/ParDataAuthority.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsDetailsForm.php
- web/modules/features/par_search_partnership_flows/src/Controller/ParPartnershipPageController.php
This is the restructuring of the partnership pages _only_. There is a further ticket to turn this page into components so that we don't have to update this information in multiple places but we can get to that later.
> PAR-1502: Updated partnership information.

- sync/views.view.partnership_search.yml
> Par 1511 partnership search

- web/modules/custom/par_data/src/Entity/ParDataInspectionPlan.php
Prevent system loop hole for inspection plans being re-activated indirectly.
> Par 1499 inspection plan auto restore

- web/modules/custom/par_data/par_data.install
- web/modules/custom/par_data/src/Entity/ParDataLegalEntity.php
@jon-edery What do you think of this, de-duping the legal entities at the stage they're created, I can't forsee any issues as a legal entity will always be returned from `ParDataLegalEntity::create()`, it just might not be a new one.
> PAR-1527: Added de-duping of legal entity numbers.

- web/modules/custom/par_data/src/Entity/ParDataLegalEntity.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsLegalEntityForm.php
> PAR-1540 legal entity restrictions

- sync/views.view.advice_lists.yml
> PAR-1556: Updated advice listings order

- sync/user.role.authenticated.yml
- sync/user.role.par_authority_manager.yml
- sync/user.role.senior_administration_officer.yml
- sync/views.view.helpdesk_authorities.yml
- web/modules/custom/par_forms/src/Plugin/ParForm/ParUserDetail.php
- web/modules/custom/par_roles/par_roles.module
- web/modules/custom/par_roles/par_roles.permissions.yml
- web/modules/features/par_profile_update_flows/par_profile_update_flows.permissions.yml
PAR-1608: Displaying of authority manager role on profile page
PAR-1631: Displaying 'add an authority' link when no search results
> V40.0 fixes

- sync/field.field.par_data_authority.authority.field_regulatory_function.yml
- web/modules/custom/par_forms/src/Plugin/ParForm/ParSelectRegulatoryFunctionsForm.php
- web/modules/features/par_data_config/config/install/field.field.par_data_authority.authority.field_regulatory_function.yml
Prevent users creating authorities without regulatory functions.
> PAR-1673 reg functions

- web/modules/custom/par_data/par_data.install
- web/modules/custom/par_data/src/Entity/ParDataEntity.php
- web/modules/custom/par_data/tests/src/Kernel/ParDataTestBase.php
- web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsArchiveConfirmForm.php
> PAR-1670 archive reason validation

- web/themes/custom/par_theme/sass/_accessibility.scss
- web/themes/custom/par_theme/sass/par.scss
This is for sure a temporary fix, the only permanent fix is to upgrade the entire GDS library which will be a fair bit of work.
> PAR-1675: Accessibility Issue WCAG1.4.11 Non-text Contrast.

- web/modules/custom/par_forms/src/Plugin/ParForm/ParPartnershipDocuments.php
> Hotfix 50.1.0

- .circleci/config.yml
- composer.json
- composer.lock
- docker-compose.yml
- scripts/db-backup.sh
- scripts/db-remote-backup.sh
- web/drush/sites/par.site.yml
- web/sites/all/drush/drush.yml
We now have a new seed database generated nightly alongside the original sanitisation scripts. This dumps while excluding the following columns:
https://github.com/UKGovernmentBEIS/beis-primary-authority-register/pull/837/files#diff-165e52939fe0020253c5ad14bd2be5babe6082b21b08f04728d8987186f6eb6cR44
> PAR-1764: Updated database dump scripts to ignore data.

- README.md
- phpcs.xml.dist
To sniff all custom code run:
```
./vendor/bin/phpcs web/modules/custom web/modules/features web/themes/custom
```
Any new PRs should be tested for coding standard rules, although there's no need to bust out gut over code sniffer rules.
Documentation added to the README for this.
> Create phpcs.xml.dist to enable easy sniffing of code.

- .circleci/config.yml
- web/modules/custom/par_data/src/Plugin/views/field/ParFlowLink.php
BUG - https://regulatorydelivery.atlassian.net/browse/PAR-1789
> PAR-1789: Partnership flow link not working on cached pages

- web/modules/features/par_dashboards/src/Controller/ParDashboardsDashboardController.php
- web/modules/features/par_dashboards/src/ParDashboardComponents.php
- Updates the /dashboard page to remove fieldset that do not contain form items and replaces them with containers and h2 headers
> PAR-1549: Removing fieldset elements when they do not contain form items

- sync/google_analytics.settings.yml
Added the new G4 analytics property to allow analytics to be captured with the new Google Analytics 4 service.
> PAR-2153: Added new Google Analytics property

- sync/core.date_format.gds_date_format.yml
- sync/par_data.par_data_partnership_legal_entity_type.partnership_legal_entity.yml
- sync/search_api.index.partnership_index.yml
- tests/features/6-user-journey-coordinator-user-update-partnership.feature
- web/modules/custom/par_data/par_data.install
- web/modules/custom/par_data/src/Entity/ParDataEntity.php
- web/modules/custom/par_data/src/Entity/ParDataPartnership.php
- web/modules/custom/par_data/src/Entity/ParDataPartnershipLegalEntity.php
- web/modules/custom/par_data_test/content/par_data_partnership_le/20bf74d8-9f5c-4e59-99c1-c728dcd3c581.yml
- web/modules/custom/par_data_test/content/par_data_partnership_le/335e9625-ef40-4027-aa6a-5e63e02c8509.yml
- web/modules/custom/par_data_test/content/par_data_partnership_le/3ee8eede-8c8d-4ce3-b9c5-a32865e51855.yml
- web/modules/custom/par_data_test/content/par_data_partnership_le/5f992bf3-984e-41ea-813f-9f423f322343.yml
- web/modules/custom/par_data_test/content/par_data_partnership_le/754aafb5-b995-4c78-9fd9-ee27132bbd8d.yml
- web/modules/custom/par_data_test/content/par_data_partnership_le/7c2338fd-6b74-4992-bc6f-fa3ed8821365.yml
- web/modules/custom/par_data_test/content/par_data_partnership_le/8e630f21-ac88-4844-b82d-9f8512419dce.yml
- web/modules/custom/par_data_test/content/par_data_partnership_le/a17d7fa3-cfda-46a7-b89d-1e42d2db7294.yml
- web/modules/custom/par_data_test/content/par_data_partnership_le/c1a82f9a-ab27-45db-81ba-427478c90d69.yml
- web/modules/custom/par_flows/src/ParRedirectTrait.php
- web/modules/custom/par_forms/src/Plugin/ParForm/ParPartnershipLegalEntityDisplay.php
- web/modules/features/par_data_config/config/install/par_data.par_data_partnership_legal_entity_type.partnership_legal_entity.yml
- web/modules/features/par_member_upload_flows/src/Controller/ParMemberDownload.php
- web/modules/features/par_member_upload_flows/src/ParMemberCsvHandler.php
- web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskApproveRegulatoryFunctionsForm.php
A side effect of adding the new status field is that we need a way to display this:
For comparison this is what it used to look like:
> PAR-2038: Added a status field to partnership legal entities.

- tests/e2e/par-test-automation/src/main/java/uk/gov/beis/pageobjects/PartnershipConfirmationPage.java
- tests/e2e/par-test-automation/src/main/java/uk/gov/beis/pageobjects/PartnershipDescriptionPage.java
- tests/e2e/par-test-automation/src/main/java/uk/gov/beis/pageobjects/TradingPage.java
- tests/e2e/par-test-automation/src/main/java/uk/gov/beis/stepdefs/PARStepDefs.java
- tests/e2e/par-test-automation/src/test/resources/features/PAR-General.feature
Code clean-up and test fixes.
All fixed tests are passing correctly.
> Par 2253 toms test fix

- sync/views.view.notifications.yml
Adds content to empty 'Actions' table cell
https://regulatorydelivery.atlassian.net/browse/PAR-2475
Visit 'Dashboard' page and validate the table cells are not empty and have meaningful content
> PAR-2449 - Adding content for empty table cells

- web/modules/custom/par_forms/src/Plugin/ParForm/ParEnforcementActionForm.php
Marks the field upload field as optional
https://regulatorydelivery.atlassian.net/browse/PAR-2181
Followed steps to recreate from JIRA tasks
> PAR-2181 - Adding optional label to form field

- tests/e2e/par-test-automation/src/test/java/uk/gov/beis/test/PARTestRunner.java
- tests/e2e/par-test-automation/src/test/resources/features/HappyPathsOther.feature
Updated the report generation to get Cucumber HTML report
> Fixed a failure in User journey sad path

- .circleci/config.yml
- devops/cf/push.local.sh
> PAR-2521: CircleCI and deploy specific

- .gitignore
- phpunit.xml.dist
- web/modules/custom/par_data/src/ParDataStorage.php
- web/modules/custom/par_data/tests/src/Kernel/Access/AccessParPartnershipsTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityMergeTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParAuthorityTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParCommonTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParDeviationRequestTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParEnforcementNoticeTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParGeneralEnquiryTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParInspectionFeedbackTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParOrganisationTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParPartnershipTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityParPersonTest.php
- web/modules/custom/par_data/tests/src/Kernel/Entity/EntityQueryCaseInsensitivityTest.php
- web/modules/custom/par_data/tests/src/Kernel/ParDataTestBase.php
- web/modules/custom/par_roles/par_roles.module
- web/modules/custom/par_validation/src/Plugin/Validation/Constraint/ParRequiredValidator.php
Updated the test code so that more automated testing could be used to see if there is issues the updated services.
Some changes in the files are to reduced the number of PHPCS Errors and warnings for the changed file.
See https://regulatorydelivery.atlassian.net/browse/PAR-2543
> PAR-2543 Site addons services check Base upon the release March 25 branch

- scripts/sanitise-par-people.sh
- web/modules/custom/par_data/src/Drush/Commands/ParDataCommands.php
https://regulatorydelivery.atlassian.net/browse/PAR-2509
Updated the code so that the updates are only proformed once.
The query() and the execute() meant it was beening done twice.
Replaced the drush aliases with the full test to improved readablility.
The file now produces no warning or errors hen checked by PHPCS.
> PAR-2509 fix the 'build test deploy' pipeline as it constantly fails

- .circleci/config.yml
- devops/cf/push.local.sh
- sync-dev/ultimate_cron.job.dblog_cron.yml
- sync-dev/ultimate_cron.job.update_cron.yml
- sync-migration/.htaccess
- sync-migration/core.date_format.json_api.yml
- sync-migration/rest_api_authentication.settings.yml
- sync-migration/user.role.json_api_consumer.yml
- sync-migration/views.view.json_api_par_authorities.yml
- sync-migration/views.view.json_api_par_organisations.yml
- sync-migration/views.view.json_api_par_users.yml
- sync-migration/views.view.json_api_people.yml
- sync-migration/views.view.la_reg_functions.yml
- sync-migration/views.view.par_co_ordinated_business.yml
- sync-migration/views.view.par_co_ordinated_partnership.yml
- sync-migration/views.view.partnership_members_list.yml
- sync-migration/views.view.users_in_multiple_partnerships.yml
- sync-migration/views.view.users_with_multiple.yml
- sync/config_split.config_split.dev_config.yml
- sync/config_split.config_split.migration_config.yml
- sync/views.view.advanced_partnership_search.yml
- web/sites/default/settings.php
- Added to the sync-migration directory, configuration that is only found on the Migration environment.
- Updated the CI so that the requested database is present on that environment.
- Updated settings so that VCAP_SERVICES and in the future DATABASE_SERVICES environment variable which have JSON encoded information can be used. when using Docksal and possibly connect only using the configured transport layer protocol. It default to tls if not set.
[JIRA issue PAR-2570](https://regulatorydelivery.atlassian.net/browse/PAR-2570)
> PAR-2570 Migration env DB work
