OfficeForProductSafetyAndStandards/beis-primary-authority-register

sync/views.view.helpdesk_dashboard.yml
sync/views.view.partnership_search.yml
web/themes/custom/par_theme/templates/views-view-table.html.twig

Views table now support captions for things like "Search results". It is configurable in the views UI.
These views also needed reexporting as contained erroneous fields.

Implementing GDS Captions

---

Vagrantfile
docker/destroy-dependencies.sh
docker/setup.sh

To keep in line with our Docker on Travis, I have implemented an NFS uid/gid flag for OS X. It is untested on Linux though, so would be good to make sure it works on Linux as well with the flag I found. (BSD NFS vs Linux NFS)
What this does improve is now there shouldn't be a need to delete any system files or clone the repo again or use any handy scripts.
It will speed up vagrant build and also at any time you can now run `vagrant up --provision` to get a clean Drupal instance (with a new database et al)

Vagrant should run as host uid/gid for file permissions.

---

web/themes/custom/par_theme/templates/page-title.html.twig

Even though most views seem to have had their titles changes either not merged in or purposefully reverted, it now supports GDS split titles again.
*testing notes*
1. edit a view title to have "First bit of title | Second bit of title"
2. view page to confirm title looks like as intended below.

Views to support the GDS split titles

---

Vagrantfile
docker/destroy-dependencies.sh
docker/setup.sh
vagrant.sh

To test this:
1. Checkout the branch
2. cd ..
3. Add a line to vagrant.sh to checkout the branch after it clones the repo
4. sh beis-primary-authority-register/vagrant.sh
The new Vagrant box differs only in that it has all the Docker packages pre-installed.
The new vagrant.sh file must be run from the directory above the repo. It will do a few helpful things
1) Save your environment file
2) Destroy the VM and clear away conflicting processes
3) Install Composer dependencies on the host and the fix the permissions for the VM and Docker

New Vagrant box and a helper script for rebuilding the environment

---

.travis.yml

Borrowed from some other open source projects, using this seems to be a workaround for the Travis stdout write-gate.

Write errors on latest Trusty build

---

sync/par_flows.par_flow.revoke_partnership.yml
tests/src/features/92-partnerships-approval-helpdesk-user.feature
web/modules/custom/par_data/src/Entity/ParDataAdvice.php
web/modules/custom/par_data/src/Entity/ParDataPartnership.php
web/modules/features/par_rd_help_desk_flows/config/install/par_flows.par_flow.revoke_partnership.yml
web/modules/features/par_rd_help_desk_flows/par_rd_help_desk_flows.routing.yml
web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskRevokeConfirmForm.php
web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskRevokeForm.php

This is the initial work to create the pages for the revocation journey (just the pages and the flow, no link to it yet so the journey can't really be used even if we merge this):
The titles and various texty bits on the pages are a bit of a mess really, there's very little consistency of wording between these two pages or even between the approve journey but we can address when everyone is in next week.

PAR-1059 & PAR-1062: Added pages for partnership revocation.

---

web/modules/custom/par_data/src/Entity/ParDataEnforcementAction.php
web/modules/custom/par_data/src/Entity/ParDataEnforcementNotice.php
web/modules/custom/par_data/src/Entity/ParDataEntity.php
web/modules/custom/par_data/src/Entity/ParDataEntityInterface.php
web/modules/custom/par_data/src/Entity/ParDataPartnership.php
web/modules/features/par_enforcement_flows/src/Controller/ParEnforcementFlowsCompletedEnforcementController.php
web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskRevokeConfirmForm.php

Added an `inProgress` method for determining when an entity may be revoked, archived or deleted.
However, because we're using access control to deny access to the page if the operation cannot be performed then the actual message in the UI (PAR-1060) never really gets displayed, what happens instead is that the link is never offered on the dashboard. This has been the practice for the approval journey and various other journeys so I think best to stick with this, but it does change the A/C a little.

PAR-1060 & PAR-1043: Partnerships that are in progress cannot be revoked.

---

sync/views.view.helpdesk_dashboard.yml
web/modules/custom/par_data/src/Entity/ParDataEntity.php
web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskApproveConfirmForm.php
web/modules/features/par_rd_help_desk_flows/src/Form/ParRdHelpDeskRevokeConfirmForm.php

See screenshot for the revoked search filter option and the revoke partnership link.

PAR-1057 RD dashboard: Add 'Revoked' to partnership search filter and link to revoke partnership.

---

web/modules/custom/par_forms/src/Element/GdsDate.php
web/modules/custom/par_forms/templates/gds-date.html.twig

for use…
`$form['blah'] = [
'#type' => 'gds_date',
'#title' => 'blah',
];`

adding support for GDS date, #title etc

---

sync/core.entity_view_display.par_data_coordinated_business.coordinated_business.default.yml
sync/core.entity_view_display.par_data_coordinated_business.coordinated_business.full.yml
sync/core.entity_view_display.par_data_coordinated_business.coordinated_business.summary.yml
sync/core.entity_view_display.par_data_coordinated_business.coordinated_business.title.yml
sync/core.entity_view_mode.par_data_coordinated_business.full.yml
sync/core.entity_view_mode.par_data_coordinated_business.summary.yml
sync/core.entity_view_mode.par_data_coordinated_business.title.yml
sync/par_flows.par_flow.member_add.yml
web/modules/custom/par_forms/par_forms.module
web/modules/custom/par_forms/src/Element/GdsDate.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParBeginDateForm.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParCoveredByPlanForm.php
web/modules/custom/par_forms/templates/gds-date.html.twig
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_coordinated_business.coordinated_business.default.yml
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_coordinated_business.coordinated_business.full.yml
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_coordinated_business.coordinated_business.summary.yml
web/modules/features/par_data_config/config/install/core.entity_view_display.par_data_coordinated_business.coordinated_business.title.yml
web/modules/features/par_data_config/config/install/core.entity_view_mode.par_data_coordinated_business.full.yml
web/modules/features/par_data_config/config/install/core.entity_view_mode.par_data_coordinated_business.summary.yml
web/modules/features/par_data_config/config/install/core.entity_view_mode.par_data_coordinated_business.title.yml
web/modules/features/par_member_add_flows/config/install/par_flows.par_flow.member_add.yml
web/modules/features/par_member_add_flows/src/Form/ParConfirmationReviewForm.php

```
$form['blah'] = [
'#type' => 'gds_date',
'#title' => 'blah',
'#default_value' => ['day' => 12, 'month' => 3, 'year' => 2016],
];
```
Ignore everything in the `/sync` directory, this is all in the feature anyway, start review at https://github.com/UKGovernmentBEIS/beis-primary-authority-register/pull/201/files#diff-9b3a6f4e2ccb9d7b1ec36cc6c1aa33eb
And you can almost ignore everything in the feature `par_data_config` because it's all just setting up view displays for the `par_data_coordinated_business` entity which hasn't been done before and is pretty trivial.

PAR-1134: Added new gds date form element

---

.bp-config/options.json

This removes the deprecated PHP_EXTENSIONS directive from the PaaS options.json file.

Remove PHP_EXTENSIONS directive from options.json

---

web/modules/features/par_member_cease_flows/src/Form/ParMemberCeaseConfirmForm.php

Confirmation screens don't need access checking.

Access fix: Updated cease journey access.

---

sync/views.view.advice_lists.yml

It appears that views will only do an access check on the primary listed entity and not the relationships. Because the advice views list the advice on a partnership it's therefore only checking the partnership for access.
This seems to be the easiest and best solution. We'll have to think about how to handle deleted entities better at a later date anyway.

PAR-1462: Updated advice views.

---

sync/views.view.helpdesk_dashboard.yml

The partnership status being shown in the export was the status of the first revision of the entity, and therefore mostly incorrect.

PAR-1533: Updated csv partnership status.

---

sync/user.role.par_authority.yml
sync/user.role.par_helpdesk.yml
sync/user.role.par_organisation.yml
sync/views.view.par_people.yml
tests/features/user-management.feature
web/modules/custom/par_data/par_data.install
web/modules/custom/par_data/par_data.module
web/modules/custom/par_data/src/Entity/ParDataPerson.php
web/modules/custom/par_data/src/Entity/ParDataPersonInterface.php
web/modules/custom/par_data/src/ParDataStorage.php
web/modules/custom/par_data/src/Plugin/views/field/ParPersonAccountEmail.php
web/modules/custom/par_data/src/Views/ParDataViewsData.php
web/modules/custom/par_data/tests/src/Kernel/Entity/EntityMergeTest.php
web/modules/custom/par_roles/par_roles.module
web/modules/custom/par_roles/par_roles.permissions.yml
web/modules/features/par_person_merge_flows/src/Form/ParMergePeopleForm.php
web/modules/features/par_person_merge_flows/src/ParFlowAccessTrait.php
web/modules/features/par_profile_view_flows/src/Controller/ParProfileController.php

* lower cased all people email addresses (resolves issues with aggregation in views)
* changed the way that similar people are looked up** see `ParDataPerson::getSimilarPeople()`
* grouped views by person email address and user account email address (allows for management of all cases)
** it is important that 'similar' people are looked up in the correct way, this avoids a mix and match of people and user accounts, the table below sums up the complexities:
Person Id | Person Email | User account email (linked on field_user_account)
------------ | ------------ | -------------
1 | 1@ | -
2 | 1@ | 1@
3 | 1@ | 2@
4 | 2@ | -
5 | 2@ | 1@
6 | 2@ | 2@
This is a perfectly acceptable situation, it arises from the need:
* to link all person email addresses with user accounts that have a matching …

PAR-1624: Improved the association of people with their user accounts

---

composer.lock
sync/filter.format.plain_text.yml
web/modules/custom/par_data/par_data.install
web/modules/custom/par_data/src/Entity/ParDataEntity.php
web/modules/custom/par_data/src/ParDataStorage.php
web/modules/custom/par_flows/src/ParFlowDataHandler.php
web/modules/custom/par_flows/src/ParFlowDataHandlerInterface.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParAboutBusinessForm.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParAboutPartnershipForm.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParContactDetailsFullForm.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParContactPreferencesForm.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParDeviationRequestForm.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParEnquiryForm.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParInspectionFeedbackForm.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParInspectionPlanForm.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParMessageForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAboutBusinessForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAboutForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsAdviceForm.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsInspectionPlanForm.php

There are three things that need to happen simultaneously to make sure we don't get filter inputs in the text area:
1. Save the format `plain_text` every time.
2. Don't call `getString()` to but `get('value')->getValue()` and extract the raw value instead of the combined value.
3. Sanitise all existing cases where the filter input is already in the field value as per the hook_8044
If we don't do 1) then all the current values that have been saved _without_ a format will 'assume' a format when next that page is edited in the CKeditor, and usually they'll assume the wrong format (hence the missing formatting).
If we don't do 2) then all the current values that have been saved _with_ a format will output string+format when next they are edited in any of the journeys... and they will …

PAR-1618: Updated plain text filtering.

---

web/modules/features/par_member_add_flows/src/ParFlowAccessTrait.php
web/modules/features/par_member_update_flows/src/ParFlowAccessTrait.php
web/modules/features/par_member_upload_flows/src/ParFlowAccessTrait.php
web/modules/features/par_partnership_contact_add_flows/src/Form/ParReviewForm.php
web/modules/features/par_partnership_contact_add_flows/src/ParFlowAccessTrait.php
web/modules/features/par_partnership_contact_remove_flows/src/ParFlowAccessTrait.php
web/modules/features/par_partnership_contact_update_flows/src/ParFlowAccessTrait.php

To reference one instance where this check is already being used - https://github.com/UKGovernmentBEIS/beis-primary-authority-register/blob/master/web/modules/features/par_partnership_flows/src/ParPartnershipFlowAccessTrait.php#L38
We just forgot to apply this to all the spin-off partnership management journeys.

PAR-1632: Updated permissions for managing partnership contacts.

---

.circleci/config.yml
web/themes/custom/par_theme/par_theme.libraries.yml
web/themes/custom/par_theme/sass/par.scss

Not sure if we need to explicitly set display block styling for par flow links?  
removing this styling does not seem to change the fact that the elements are still displaying as a block element 
(like <p>) with each flow link displays on a new line.
Removing this prevents the element highlighting the whole length which looks quite bad.
display: table can also be used to put the element on a new line but with out the whole length issue.. 
Updated SCSS:

PAR-1653  

---

web/modules/custom/par_data/par_data.install
web/modules/custom/par_data/src/Entity/ParDataInspectionPlan.php
web/modules/custom/par_data/src/Entity/ParDataPerson.php
web/modules/custom/par_data/src/ParDataStorage.php
web/modules/custom/par_data/tests/src/Kernel/ParDataTestBase.php
web/modules/custom/par_data_test/content/par_data_advice/12efa979-5e8c-4144-b3bd-fa001ab4dd54.json
web/modules/custom/par_data_test/content/par_data_advice/65b1f3b2-5e95-4b73-8a81-f536e6a24530.json
web/modules/custom/par_data_test/content/par_data_advice/a8e472b0-3853-4437-b987-263c0e054b99.json

I've made the email a required field for all contacts.
@jon-edery this also will now throw an error if we try to save an entity which doesn't have all the required properties. On the whole I think this is probably a good thing, but there may be some situations where we are creating empty entities for updating later.
My thoughts on this are that if we are then that field probably shouldn't be required in the first place, and the tests should show us where this is happening. But this is a bit of a heavy handed approach. Thoughts?

PAR-1637: Made email a required field for all contacts

---

web/themes/custom/par_theme/templates/page.html.twig

This resolves issues with the skip link not linking to the main page title.

PAR-1674: Accessibility fix - WCAG2.4.1 Bypass Blocks

---

web/modules/features/par_dashboards/src/Controller/ParDashboardsDashboardController.php
web/themes/custom/par_theme/par_theme.libraries.yml
web/themes/custom/par_theme/par_theme.theme
web/themes/custom/par_theme/sass/par.scss

This resolves issues with the dashboard page and the homepage sharing a name = 'Primary Authority Register'
We have changed the dashboard title to Dashboard. And also introduced some logic to make sure the site name 'Primary Authority Register' is a) de-prioritised in the html title tag b) no repeated in the html title tag.

PAR-1545: Accessibility issue WCAG2.4.2 Page titled

---

.circleci/config.yml
devops/cf/push.local.sh
sync/raven.settings.yml
web/modules/custom/par_log/par_log.info.yml
web/modules/custom/par_log/par_log.services.yml
web/modules/custom/par_login/par_login.info.yml
web/modules/custom/par_login/par_login.services.yml
web/modules/custom/par_login/src/EventSubscriber/ProfilePageRedirectSubscriber.php
web/modules/custom/par_login/src/Routing/ParUserRouteSubscriber.php

Added automatic redirection of users from _their_ profile pages to the dashboard.
Added improved logging to track down why they were directed to their profile page in the first place.
According to the login_destination rule 'dashboard' all authenticated users should be redirected to the dashboard after 'login' and 'one-time-login'... I guess it's possible this isn't working all the time, or that the invite system is logging people in in a different way, or perhaps there's some other bug in it. It would be good to test every single way of logging into the system.

PAR-1698: Automatic redirection from profile pages to dashboard

---

web/modules/custom/par_data/src/Entity/ParDataPartnership.php
web/modules/custom/par_data/src/Entity/ParDataPartnershipLegalEntity.php
web/modules/features/par_partnership_flows/src/Form/ParPartnershipFlowsLegalEntityReinstateForm.php

Partnership legal entity reinstate form can no longer be accessed if the PLE can not be reinstated.
Add validation to partnership legal entity reinstate form to double check that reinstating is OK.

Par 1906 user able to add duplicate legal entity after reinstating

---

web/modules/custom/par_notification/src/ParRecipient.php
web/modules/custom/par_notification/src/ParSubscriptionManager.php

Remove the permission filter on subscribed recipients, we introduced a check so that email addresses that did not have user accounts could not receive notifications about sensitive data in PAR.
We've not removed this restriction again following user feedback and an evaluation that some users have notifications sent to a shared inbox, but then sign in using a personal email address when they click the notification link.

PAR-2149: Removed permissions restrictions on who can receive notifications

---

composer.json
composer.lock
patches/govuk-theme-classes.patch
sync/chosen.settings.yml
sync/core.extension.yml
web/modules/custom/par_forms/src/Plugin/ParForm/ParAddressForm.php

- Removes chosen from the front end (its not good for accessibility)
- Introduces a11y_autocomplete_element module and required drupal package
- Swaps out the Country select for the 'a11y_autocomplete' form element
- Adds a patch to add the additional classes required by govuk-theme

PAR-1541: Country Autocomplete (chosen replacement)

---

sync/views.view.advanced_partnership_search.yml
sync/views.view.notifications.yml
sync/views.view.par_user_authorities.yml
sync/views.view.par_user_organisations.yml
sync/views.view.par_user_partnerships.yml
sync/views.view.partnership_search.yml
sync/views.view.primary_authority_register.yml
web/themes/custom/par_theme/par_theme.theme

Updates the page title to include view title in the theme_preprocess 
- Updates views titles that has incorrect duplication { view_name } \ Primary Authority Register'
https://regulatorydelivery.atlassian.net/browse/PAR-2450
Checked through the site, only pages driven by views suffered the issue

PAR-2450 - Updating page title to use view title

---

web/modules/features/par_partnership_document_remove_flows/src/Form/ParRemoveAdviceForm.php

Adding error message and required error UI to advice removal
Makes the textarea required, which triggers the error class and necessary UI 
https://regulatorydelivery.atlassian.net/browse/PAR-2341
Followed steps to recreate from JIRA tasks

PAR-2341 - Adding required field for removing advice reason

---

web/themes/custom/par_theme/sass/_overrides.scss

Adding a large margin top specifically on add-button
Updates the spacing between the input and the add button
https://regulatorydelivery.atlassian.net/browse/PAR-2350
Followed steps to recreate from JIRA tasks

PAR-2350 - Organisation UI defects

---

composer.json
sync/views.view.members_list.yml
web/modules/features/par_partnership_document_remove_flows/src/Form/ParRemoveInspectionPlanForm.php

Fixes import issues with flysystem php error and updates Drupal view
- Patches PHP issues with the flysystem, see https://github.com/twistor/flysystem-stream-wrapper/issues/27 & https://www.drupal.org/project/flysystem/issues/3387094
- Updates Drupal view to display legal entities
https://regulatorydelivery.atlassian.net/browse/PAR-2365
Follow steps in the JIRA tasks

PAR-2365 - Legal Entities and Trading Names are not displayed for Members uploaded from a CSV File

---

web/modules/features/par_partnership_document_remove_flows/src/Form/ParRemoveInspectionPlanForm.php

Adding error message and required error UI to inspection plan removal
Makes the textarea required, which triggers the error class and necessary UI 
https://regulatorydelivery.atlassian.net/browse/PAR-2340
Followed steps to recreate from JIRA tasks

PAR-2340 - Adding error message to removal of inspection plan

---

web/modules/custom/par_data/src/ParDataManager.php

Location	https://beis-par-staging.cloudapps.digital/partnership/apply/review Referrer	https://beis-par-staging.cloudapps.digital/partnership/apply/invite Message	TypeError: Drupal\par_data\ParDataManager::getUserPerson(): Argument #2 ($entity) must be of type Drupal\par_data\Entity\ParDataPerson, Drupal\par_data\Entity\ParDataAuthority given, called in /home/vcap/app/web/modules/features/par_partnership_application_flows/src/Form/ParConfirmationReviewForm.php on line 287 in Drupal\par_data\ParDataManager->getUserPerson() (line 945 of /home/vcap/app/web/modules/custom/par_data/src/ParDataManager.php).
https://beis-par-staging.cloudapps.digital/admin/reports/dblog/event/1064

Backout the change that causes this error

---

web/modules/custom/par_subscriptions/src/Event/SubscriptionEvent.php

Update so that the entity variable is not duplicated with one in the class hierarchy.
See web/modules/contrib/hook_event_dispatcher/modules/core_event_dispatcher/src/Event/Entity/AbstractEntityEvent.php
Add documentation so that PHPCS does not report Errors or Warning for this file.

Par Subscription Event Error

---

web/modules/custom/par_forms/src/Plugin/ParForm/ParSicCodeDisplay.php
web/modules/custom/par_forms/src/Plugin/ParForm/ParTradingNameDisplay.php

The two Operation Links are for 
- 'remove_field_sic_code'
- 'remove_trading_name'
They are not implmented and the exception is logged everytime the page is rendered.

Remove the code that adds these Operation Links 
